// <auto-generated />
namespace FriendlyLinks.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class fina : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fina));
        
        string IMigrationMetadata.Id
        {
            get { return "202108022203186_fina"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
